spring.application.name=bodegabackend
server.port=8080

# ===============================
# CONEXIÓN A POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/bodegabackend
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ===============================
# 1. MEJORA VISUAL EN LA CONSOLA
# ===============================
# Formatea el SQL para que no sea una sola línea larga y se pueda leer bien
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 2. LIMPIEZA DE ADVERTENCIAS
# ===============================
# Quita la advertencia amarilla "open-in-view is enabled by default" que sale al iniciar Tomcat
spring.jpa.open-in-view=false

# ===============================
# 3. SEGURIDAD (CRUCIAL PARA REACT)
# ===============================
# Apaga el login automático de Spring Security temporalmente para que React pueda consumir tus APIs sin ser bloqueado
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration